POST localhost:8080/portal/search
Content-Type: application/json

{
  "query": {
    "query_string": {
      "query": "test",
      "default_field": "content"
    }
  },
  "fields": [
    "title", "t01_object.obj_id"
  ],
  "_source": false,
  "size": 1,
  "aggs": {
    "my-agg-name": {
      "terms": {
        "field": "iPlugId"
      }
    }
  }
}