
ktor:
  development: true
  application:
    modules: 
      - de.ingrid.ingridapi.ApplicationKt.base
      - de.ingrid.ingridapi.ApplicationKt.module1
      - de.ingrid.ingridapi.ApplicationKt.module2
  deployment:
    port: 8080
    watch: 
      - classes
      - resources
  elasticsearch:
    host: "${ES_HOST}:localhost"
    port: "${ES_PORT}:9200"