
ktor:
  development: true
  application:
    modules:
      - de.ingrid.ingridapi.ApplicationKt.base
      - de.ingrid.ingridapi.ApplicationKt.portal
#      - de.ingrid.ingridapi.ApplicationKt.module2
  deployment:
    port: 8080
    watch:
      - classes
      - resources
    rootPath: "$CONTEXT_PATH:"
  elasticsearch:
    host: "$ES_HOST:localhost"
    port: "$ES_PORT:9200"
    https: "$ES_HTTPS:false"
    username: "$ES_USERNAME:"
    password: "$ES_PASSWORD:"
